"""add_status_field_to_resume_evaluations

Revision ID: 079c42b7a8b8
Revises: f27d82e47add
Create Date: 2025-10-10 16:08:05.823575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '079c42b7a8b8'
down_revision = 'f27d82e47add'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_evaluations', sa.Column('status', sa.Enum('PENDING', 'REJECTED', 'INTERVIEW', name='resumestatus'), nullable=False, server_default='PENDING'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_evaluations', 'status')
    # ### end Alembic commands ###