"""Remove duplicate experience column, keep experience_level

Revision ID: 179fbee40885
Revises: 4ea2fce1185c
Create Date: 2025-10-06 17:29:01.667018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179fbee40885'
down_revision = '4ea2fce1185c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'experience')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('experience', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###