"""add scoring_criteria table

Revision ID: 2162c19eb27d
Revises: 179fbee40885
Create Date: 2025-10-06 21:13:14.113543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2162c19eb27d'
down_revision = '179fbee40885'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###