"""Add missing experience column to job_descriptions

Revision ID: 4ea2fce1185c
Revises: 92beb22227bb
Create Date: 2025-10-06 17:26:37.945461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea2fce1185c'
down_revision = '92beb22227bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('experience', sa.String(length=100), nullable=True))
    op.add_column('job_descriptions', sa.Column('education', sa.String(length=100), nullable=True))
    op.add_column('job_descriptions', sa.Column('job_type', sa.String(length=50), nullable=True))
    op.add_column('job_descriptions', sa.Column('skills', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'skills')
    op.drop_column('job_descriptions', 'job_type')
    op.drop_column('job_descriptions', 'education')
    op.drop_column('job_descriptions', 'experience')
    # ### end Alembic commands ###