"""add_resume_evaluations_table

Revision ID: f27d82e47add
Revises: 2162c19eb27d
Create Date: 2025-10-07 11:33:52.385299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27d82e47add'
down_revision = '2162c19eb27d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###